# Generated by Django 5.0.4 on 2024-04-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('services', models.TextField()),
                ('budget_range', models.CharField(max_length=100)),
                ('timeline', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, upload_to='contact_files/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FreelancePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('platform_icon', models.ImageField(upload_to='platform_icons/')),
                ('platform_link', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='social_icons/')),
                ('link', models.URLField(unique=True)),
            ],
        ),
    ]
