# Generated by Django 5.0.4 on 2024-07-04 01:58

import django.core.validators
import portfolio_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_contactdetails_contactus_freelanceplatform_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='file',
            field=models.FileField(blank=True, upload_to='contact_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(upload_to='portfolio/portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='video',
            field=models.FileField(blank=True, upload_to='portfolio/portfolio_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm']), portfolio_app.utils.validate_video]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, upload_to='testimonial_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv', 'flv', 'mkv', 'webm']), portfolio_app.utils.validate_video]),
        ),
    ]
